version: '3.8'

services:
  tor-privoxy:
    restart: always
    image: dockage/tor-privoxy:latest
    ports:
      - "9050:9050" # Tor proxy
      - "9051:9051" # Tor control port
      - "8118:8118" # Privoxy
  redis:
    image: redis:7.2.4
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --requirepass LRR3SpEIH7EX1x2bZoi3
  postgres:
    image: postgres:12.17-bullseye
    environment:
      POSTGRES_DB: googlesearch
      POSTGRES_USER: googlesearchuser
      POSTGRES_PASSWORD: Dg99A617r4Mm
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
